version: '{build}'
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: dotnet restore Neptuo.sln
build:
  verbosity: quiet